### ISSUE TITLE
Handle ".php" in request path

### ISSUE THREAD

**Issue by flavioheleno** [package-health/php#126]
The current nginx/php-fpm configuration cannot handle `.php` being present in the request path.

Reproducing: by visiting the reference link below, the user will be presented with a blank page and the error "No input file specified.", which clearly demonstrates that the configuration is leading php-fpm to search for `jmespath.php` in the current path, which will fail as expected.

The expected behavior is to render the correct page (in this specific case, the redirect to the latest release) for `mtdownling/jmespath.php` package.

Reference link: https://php.package.health/packages/mtdowling/jmespath.php/latest

**Comment by flavioheleno** [comment]
Fixed by [a757e19](https://github.com/package-health/php/commit/a757e197652747b7a185d3eb41785fedb28a4728)

**Comment by flavioheleno** [comment]
Reopened as the following link still fails: https://php.package.health/packages/mtdowling/jmespath.php

**Comment by okiedork** [comment]
The problem that needs to be solved is how can we tune the regex to match actual files instead of package names?

If regex doesn't solve it, we can maybe change the code to rewrite the URL for such packages using `_` instead of `.` (or some other replacement char).

**Comment by flavioheleno** [comment]
Properly fixed by 0854db2
